# Welcome to Jekyll!
#

# Site settings
title: DK&NY
description: |
  함께 있을 때 가장 나 다운 모습이 되고  
  함께 있을 때 미래를 꿈꾸게 하는 사람을 만났습니다.  
  그 사람과 인생이라는 여행을 함께 시작하려 합니다.  
  저희 여행의 시작점에 귀한 분들을 초대하오니  
  오셔서 축복해주시면 큰 기쁨이겠습니다.
owner: 김동균
first_published: 2020.05.23 # if migrating another site, the year of your first publish
email: easteria59@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://easteria.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
